<template>
    <Layout>
            <div class="background container">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
        <div class="fade-in profile-picture-container slide-in-elliptic-top-fwd relative" data-aos="flip-right" data-aos-duration="1500">
            <picture>
                <source alt="" srcset="./../../static/images/profile-pic.webp" type="image/webp">
                <g-image class="profile-picture" src="./../../static/images/profile-pic.jpg" alt="profile picture"></g-image>
            </picture>
        </div>
        
        
        <div class="fade-in" >
            <h2 class="text-center p-3 h2">
                Frontend Engineer
            </h2>
        </div>
        <div class="bio fade-in lg:w-3/4 lg:text-2xl sm:w-3/4 mx-auto my-5" >
            <p>Hi there! I'm Linda, an engineer and designer in Lagos, Nigeria. I enjoy solving problems by creating beautiful
               and functional products. I also write and speak about web technologies. </p>          
        </div>

        <div class="fade-in inline-flex w-full justify-between">
            <h2 class="my-8 md:my-8 h2 sm:my-5"><i class="fas fa-arrow-down"></i> Latest Posts </h2>
            <a class="primary-color h3 my-auto" href="/blog" >View all</a>
        </div>

        <Latest/>
         
        <div class="footer fade-in">
            <div class="flex justify-center">
                <a href="/contact" class="button my-2 px-5 text-center text-lg">Contact Me</a> 
            </div>
            <div class="links sm:w-3/4 lg:w-1/2 mx-auto flex" >
                <p class=" inline-flex w-full justify-center mt-6">
                        <a class="md:mr-16 mr-8 flex flex-col items-center" href="https://twitter.com/LindaOjo_" title="Twitter">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                            <p>Twitter</p>
                        </a>  
                        <a class="md:mr-16 mr-8 flex flex-col items-center" href="https://github.com/LindaOjo" title="Github">
                            <i class="fa fa-github" aria-hidden="true"></i>
                            <p>Github</p>
                        </a>   
                        <a class="flex flex-col items-center" href='https://res.cloudinary.com/lindaojo/image/upload/v1601131597/Resume_Linda_Ojo_msdltz.png' title="Resume" target="_blank">
                            <i class="fas fa-file-alt" aria-hidden="true"></i>
                            <p>Resume</p>
                        </a> 
                </p>
            </div>

            <p class=" mt-6 text-center mx-5">Designed and Developed by Linda Ojo </p>
        </div> 
    </Layout>
</template>

<script> 
import Layout from '~/layouts/Default.vue';
import Latest from './../components/Latest';

export default {
     components: { 
        Layout,
        Latest
    },
    metaInfo: { title: 'Home' },
}
</script>

<style lang="scss" scoped>

:root, body, .background {
    margin: 0;
    padding: 0;
    overflow-x: hidden;
    overflow-y: hidden;
}

.background {
    position: static;
    height: 1px;
}

i {
    font-size: 1.3rem;
}

/* Mobile */
@media (max-width: 768px) {
	.fa-arrow-down {
		display: none;
	}
}

$particleSize: 10vmin;
$animationDuration: 6s;
$amount: 15;
.background span {
  width: $particleSize;
  height: $particleSize;
  border-radius: $particleSize;
  backface-visibility: hidden;
  position: fixed; /* don't change, fixes scroll bug*/
  animation-name: move;
  animation-duration: $animationDuration;
  animation-timing-function: linear;
  animation-iteration-count: infinite;
  $colors: (
    #8ec5fc5e ,
    #53a9eb62,
    #eb959524
  );
  @for $i from 1 through $amount {
    &:nth-child(#{$i}) {
      color: nth($colors, random(length($colors)));
      top: random(100) * 1%;
      left: random(100) * 1%;
      animation-duration: (random($animationDuration * 10) / 10) * 1s + 10s;
      animation-delay: random(($animationDuration + 10s) * 10) / 10 * -1s;
      transform-origin: (random(50) - 25) * 1vw (random(50) - 25) * 1vh;
      $blurRadius: (random() + 0.5) * $particleSize * 0.5;
      $x: if(random() > 0.5, -1, 1);
      box-shadow: ($particleSize * 2 * $x) 0 $blurRadius currentColor;
    }
  }
}

@keyframes move {
  100% {
    transform: translate3d(0, 0, 1px) rotate(360deg);
  }
}
/* Particles background inspired by Louis Hoebregts (https://codepen.io/Mamboleoo/pen/BxMQYQ)*/

.footer {
     @apply w-full h-auto flex flex-col items-center;
     margin-bottom: -1.5rem;
 }


 /* ----------------------------------------------
 * Generated by Animista on 2020-9-30 21:18:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-elliptic-top-fwd
 * ----------------------------------------
 */
.slide-in-elliptic-top-fwd {
	-webkit-animation: slide-in-elliptic-top-fwd 0.9s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-elliptic-top-fwd 0.9s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}


@-webkit-keyframes slide-in-elliptic-top-fwd {
  0% {
    -webkit-transform: translateY(-600px) rotateX(-30deg) scale(0);
            transform: translateY(-600px) rotateX(-30deg) scale(0);
    -webkit-transform-origin: 50% 100%;
            transform-origin: 50% 100%;
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotateX(0) scale(1);
            transform: translateY(0) rotateX(0) scale(1);
    -webkit-transform-origin: 50% 1400px;
            transform-origin: 50% 1400px;
    opacity: 1;
  }
}
@keyframes slide-in-elliptic-top-fwd {
  0% {
    -webkit-transform: translateY(-600px) rotateX(-30deg) scale(0);
            transform: translateY(-600px) rotateX(-30deg) scale(0);
    -webkit-transform-origin: 50% 100%;
            transform-origin: 50% 100%;
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotateX(0) scale(1);
            transform: translateY(0) rotateX(0) scale(1);
    -webkit-transform-origin: 50% 1400px;
            transform-origin: 50% 1400px;
    opacity: 1;
  }
}


</style>
